### ISSUE TITLE
Change default CPU clock frequency to a value <= 100 MHz

### ISSUE THREAD

**Issue by andreassinn** [RobertK66/ado-chip-175x-6x#21]
Both LPC1769 and LPC1768 microcontrollers are in use but the LPC1768 supports max. 100 MHz as CPU clock frequency (reliably). To prevent issues as unreliable UART communication and other clock related problems my suggestion is to change the clock rate initialization to 96 MHz instead of 120 MHz. 

As far as I have seen this should be easily possible by removing line https://github.com/RobertK66/ado-chip-175x-6x/blob/84a214bda24e127a7043a534a27458ddb3e8186f/ado_chip_175x_6x/src/sysinit_17xx_40xx.c#L101
and enabling 
https://github.com/RobertK66/ado-chip-175x-6x/blob/84a214bda24e127a7043a534a27458ddb3e8186f/ado_chip_175x_6x/src/sysinit_17xx_40xx.c#L102)

resulting in 96 MHz CPU clock.

**Comment by RobertK66** [comment]
Great finding! (Good that we had a Pizza to discuss on this issues ;-) ). I was not aware, that there are LPC1768 Instances around in our EM2 OBCs.
